### ISSUE TITLE
ncov-tools conda environment

### ISSUE THREAD

**Issue by raphenya** [jts/ncov-tools#28]
@jts installing `ncov-tools` with python 3.8 is taking too long to install. Currently at 80 minute log shows:
```
Building DAG of jobs...
Removing incomplete Conda environment ../ncov-tools/environment.yml...
Creating conda environment ../ncov-tools/environment.yml...
Downloading and installing remote packages.
```

**Comment by fmaguire** [comment]
It's a lot less painful with mamba, I think it's resolving the r packages
that causes the conda SAT solver to fall over.

**Comment by jts** [comment]
Unfortunately I think longer than 80 minutes is typical for conda solving the environment

**Comment by jts** [comment]
Is there a convenient way to install a collection of R packages? Maybe we should pull those out into a separate step.

**Comment by raphenya** [comment]
> Is there a convenient way to install a collection of R packages?

I will look into that and see

**Comment by DarianHole** [comment]
I found that solving the environment took a long time but was sped up for me when specified the snakemake version to <5.11.0. If I remember correctly, one of the dependencies only works with 5.10.0 of snakemake

Downloading is slow still though

**Comment by fmaguire** [comment]
`mamba env create -f environment.yml` only takes a few minutes (3:48.09) on my laptop

[mamba](https://github.com/TheSnakePit/mamba) has become the officially [recommended](https://snakemake.readthedocs.io/en/stable/getting_started/installation.html) way to install snakemake due to this and weird version pinning issues.

Honestly, just updating the documentation using the bits from the snakemake documentation might be the easiest solution.

**Comment by jts** [comment]
That works for me! Thanks

**Comment by jts** [comment]
Merged
