### ISSUE TITLE
tmp_bam rule

### ISSUE THREAD

**Issue by mcroxen** [jts/ncov-tools#35]
Two observations:

1. tmp_bam seems to have a hard-coded bam_pattern, and so if bam_pattern in your config.yaml differs, it will throw errors.
2. should tmp_bam be removed after the pipeline finishes?

**Comment by jts** [comment]
Hi Matt,

Can you paste the error that you get for first part of the issue?

`tmp_bam` is a workaround because we need indexed bam files, but the nextflow pipeline doesn't create an index and we typically have read-only access to the pipeline results directory. For this reason, I'd like to keep the directories but I should rename `tmp_bam` to something nicer like `indexed_bam`.

Jared

**Comment by mcroxen** [comment]
If I was using a different suffix in my yaml:
`bam_pattern: {sample}.somethingelse.bam`

the `get_primer_trimmed_bam_for_sample` called by `make_tmp_bam` rule (line 333) is looking for `{sample}.primertrimmed.rg.sorted.bam ` (ont) or `{sample}.mapped.primertrimmed.sorted.bam` (illumina), which may not always match the bam_pattern from config.yaml.

**Comment by jts** [comment]
Ok, I understand now. We want to enforce that the primer-trimmed bams are used for this step, to avoid misleading results in the mixture check. This uses the `platform` config value to select the right bam suffix for the typical nanopore and illumina workflows:

https://github.com/jts/ncov-tools/blob/master/qc/Snakefile#L108

Would you like us to create a new config value `primer_trimmed_bam_pattern` so that you can set this to whatever you want?

**Comment by mcroxen** [comment]
That's fair. I guess its a little unclear which bam files should be used for `bam_pattern`. If you go by the artic-ncov2019 `*.qc.csv` file they list the `*.primertrimmed.rg.sorted.bam`, perhaps suggesting that is the "final" bam, when it probably should be `*.mapped.sorted.bam`

Regardless, it may be wise to allow for that `primer_trimmed_bam_pattern`
