### ISSUE TITLE
Issue building SnpEFF database

### ISSUE THREAD

**Issue by DarianHole** [jts/ncov-tools#74]
SnpEFF seems to have updated to a new version`5.0-1` which is causing the database build to fail when it is installed instead of version `5.0-0`. 

Likely due to the line here as given to me by @kdmack87: https://github.com/jts/ncov-tools/blob/21fd71f4fc9207a592d6684997d6b66bc2d4ad3a/workflow/scripts/build_db.py#L9

I am not sure if the best solution would be to specify multiple options in the above file or to set the environment dependency to be exactly `5.0-0` (not sure if conda allows the `-` in the environment files for a version number?)

I worked around this by going into my conda environment and re-naming the folder from `5.0-1` to `5.0-0`, building the database, and then re-naming it back but that is not super ideal. Once I did this everything else still worked as intended

**Comment by jts** [comment]
@rdeborja could you look at this?

**Comment by rdeborja** [comment]
@DarianHole Previously the workflow would download the `MN908947.3` version of the snpEff files from their repository of db build leaving the `build_snpeff_db` workflow redundant.  Since the latest snpEff update, it looks like the db file is corrupt or the link is broken.  I removed the fixed version of snpEff from the script and annotation workflow so that the build will work again.  Also, it supports multiple installed versions of snpEff in a single conda environment.  I have added branch `fix_snpeff_build` to address this and submitted a PR.  Feel free to try out the branch and let me know if you run into any issues.

**Comment by rdeborja** [comment]
@DarianHole the branch has been merged and should resolve the db build issue.

**Comment by DarianHole** [comment]
Awesome, thanks! I'll run it through right now and update you with the results

**Comment by DarianHole** [comment]
Works as intended! Thanks again for the quick fixes to this and the snpEFF logs
